// frontend/src/components/LoadingSpinner.vue
<template>
  <div class="spinner-container">
    <v-progress-circular
      indeterminate
      size="48"
      color="primary"
    />
  </div>
</template>

<script setup>
/**
 * Компонент спиннера загрузки.
 */
</script>

<style scoped>
.spinner-container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100%;
  width: 100%;
}
</style>

// frontend-angular/src/app/shared/components/loading-spinner/loading-spinner.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';

@Component({
  selector: 'app-loading-spinner',
  template: `
    <div class="loading-container">
      <mat-spinner [diameter]="diameter"></mat-spinner>
      <p *ngIf="message" class="loading-message">{{ message }}</p>
    </div>
  `,
  styles: [
    `
      .loading-container {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        padding: 20px;
      }

      .loading-message {
        margin-top: 10px;
        color: #666;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, MatProgressSpinnerModule],
})
export class LoadingSpinnerComponent {
  @Input() diameter = 50;
  @Input() message = '';
}
